# Generated by Django 4.1 on 2022-09-26 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exportdocs',
            fields=[
                ('docid', models.AutoField(db_column='docId', primary_key=True, serialize=False)),
                ('invoiceno', models.CharField(db_column='invoiceNo', max_length=7)),
                ('shippingbillnumber', models.CharField(db_column='shippingBillNumber', max_length=20)),
                ('shippingbilldate', models.DateField(db_column='shippingBillDate')),
                ('exchangerate', models.DecimalField(db_column='exchangeRate', decimal_places=2, max_digits=6)),
                ('fobvalue_inr_field', models.DecimalField(db_column='fobValue(INR)', decimal_places=2, max_digits=12)),
                ('fobvalueforex', models.DecimalField(db_column='fobValueForex', decimal_places=2, max_digits=12)),
                ('dutydrawback', models.DecimalField(db_column='dutyDrawBack', decimal_places=2, max_digits=8)),
                ('blnumber', models.CharField(db_column='blNumber', max_length=15)),
                ('bldate', models.DateField(db_column='blDate')),
                ('brcno', models.CharField(db_column='brcNo', max_length=25)),
                ('brcdate', models.DateField(db_column='brcDate')),
                ('brcamtinfx', models.DecimalField(db_column='brcAmtInFx', decimal_places=2, max_digits=8)),
                ('brccurrency', models.CharField(db_column='brcCurrency', max_length=12)),
                ('egmno', models.CharField(db_column='egmNo', max_length=15)),
                ('egmdate', models.DateField(db_column='egmDate')),
                ('phytono', models.CharField(db_column='phytoNo', max_length=20)),
                ('phytodate', models.DateField(db_column='phytoDate')),
                ('courierbooking', models.CharField(db_column='courierBooking', max_length=20)),
                ('courierbookingdate', models.DateField(db_column='courierBookingDate')),
                ('trackingno', models.CharField(db_column='trackingNo', max_length=20)),
                ('poddeliverydate', models.DateField(db_column='podDeliveryDate')),
            ],
            options={
                'db_table': 'exportdocs',
                'managed': False,
            },
        ),
    ]
